application: one-crisis
version: 1
runtime: python
api_version: 1

handlers:
- url: /data
  static_dir: data
  
- url: /css
  static_dir: static/css
- url: /js
  static_dir: static/js
- url: /img
  static_dir: static/img
  
- url: /.*
  script: main.py
